# SECTION: RESOURCES - PATH
# [PATH_<NAME>] 

PATH_DATABASE = "database.sqlite"

# SECTION: DATABASE - KEYS
# [DB_KEY_<NAME>]

DB_KEY_USER_ID_LIST = "users"
DB_KEY_LOG_EVENTS_LIST  = "logs"

# SECTION: LOGS - EVENT KEYS
# [LOG_EVENT_KEY_<NAME>]

LOG_EVENT_KEY_SUCCESS = "SUCCESS_"
LOG_EVENT_KEY_WARING = "WARINING"
LOG_EVENT_KEY_ERROR = "ERROR___"
LOG_EVENT_KEY_INFO = "INFO____"

# SECTION: IDENTIFIERS - MODULE ID'S
# [API_ID_<NAME>]

API_ID_STABILITY_AI = "Stability.ai"
API_ID_LOCAL_PROCESSING = "Server machine"

